In [1]:
from numpy import *
arr1=array([
                [1,2,3,4],
                [5,6,7,8]
           ])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
from numpy import *
arr1=array([
                [1,2,3,4],
                [5,6,7,8]
           ])
print(arr1.dtype)

int32


In [3]:
from numpy import *
arr1=array([
                [1,2,3,4],
                [5,6,7,8]
           ])
print(arr1.ndim)

2


In [4]:
from numpy import *
arr1=array([
                [1,2,3,4],
                [5,6,7,8]
           ])
print(arr1.shape)

(2, 4)


In [5]:
from numpy import *
arr1=array([
                [1,2,3,4],
                [5,6,7,8]
           ])
print(arr1.size)

8


##Mul Dim To One Dim

In [6]:
from numpy import *
arr1=array([
                [1,2,3,4],
                [5,6,7,8]
           ])
arr2=arr1.flatten()
print(arr2)

[1 2 3 4 5 6 7 8]


##More Operation

In [7]:
from numpy import *
arr1=array([
                [1,2,3,4,5,6],
                [5,6,7,8,9,10]
           ])
arr2=arr1.flatten()
arr3=arr2.reshape(3,4)
print(arr3)

[[ 1  2  3  4]
 [ 5  6  5  6]
 [ 7  8  9 10]]


##3d Array Have Two 2D Array

In [8]:
from numpy import *
arr1=array([
                [1,2,3,4,5,6],
                [5,6,7,8,9,10]
           ])
arr2=arr1.flatten()
arr3=arr2.reshape(2,2,3)
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 8  9 10]]]


##Matrix Keyword

In [9]:
from numpy import *
m=matrix('1 2 3;6 4 6;2 4 6')
print(m)

[[1 2 3]
 [6 4 6]
 [2 4 6]]


##Getting Diagonal Value

In [10]:
from numpy import *
m=matrix('1 2 3;6 4 6;2 4 6')
print(diagonal(m))

[1 4 6]


##Max,Min Example

In [12]:
from numpy import *
m=matrix('1 2 3;6 4 6;2 4 6')
print(m.max())

6


##Matrix Multiplication

In [13]:
from numpy import *
m1=matrix('1 2 3;6 4 6;2 4 6')
m2=matrix('1 2 3;6 4 6;2 4 6')
m3=m1*m2
print(m3)

[[19 22 33]
 [42 52 78]
 [38 44 66]]
