In [17]:
#Problem-1
def list_concate(a,b):
    x=0
    flist=[]
    for i in a:
        for j in b:
            flist.append(i+b[x])
            x+=1
            break
    print(flist)

list1=["py","i","m","favou","lang"]
list2=["thon","s","y","rite","uage"]
list_concate(list1,list2)

['python', 'is', 'my', 'favourite', 'language']


In [16]:
#Problem-2
import numpy as np
arr = np.array([[20 ,66, 88, 12], [75 ,19, 92, 71], [27 ,90, 33, 67], [21 ,14, 25, 38], [51 ,44, 57, 77]])
newarr=arr[::2,1::2]
print(newarr)

[[66 12]
 [90 67]
 [44 77]]


In [3]:
#Problem-3
import numpy as np
array= np.arange(10, 34).reshape((8,3))
one, two, three, four = np.vsplit(array, 4)
print(one)
print(two)
print(three)
print(four)

[[10 11 12]
 [13 14 15]]
[[16 17 18]
 [19 20 21]]
[[22 23 24]
 [25 26 27]]
[[28 29 30]
 [31 32 33]]


In [13]:
#Problem-4
#expected output according to question
import numpy as np
array =np.array([[34, 43, 73],[82, 22, 12],[53, 94,66]])
print(array)

array1=array[:, np.argsort(array[1])] 
print(array1)
array2=array[np.argsort(array[:,1])]
print(array2)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[73 43 34]
 [12 22 82]
 [66 94 53]]
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [22]:
#Problem-5
class Vehicle:
    def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity=capacity
    def fare(self):
        self.capacity=self.capacity*100
        print('Fare is '+str(self.capacity))

class Bus(Vehicle) :
    def fare(self):
        self.capacity=(self.capacity*100)
        self.capacity=self.capacity+(self.capacity*.1)
        print('Fare is ' +str(self.capacity))

class MiniBus (Vehicle):
    def fare(self):
        self.capacity=(self.capacity*100)
        self.capacity=(self.capacity+(self.capacity*.1))/2
        print('Fare is ' +str (self. capacity))

obj1= Vehicle("Car", 20,30)
obj1.fare()
obj2= Bus("Western Journey",20, 30)
obj2.fare()
obj3= MiniBus(" Small Trip", 20,30)
obj3.fare()

Fare is 3000
Fare is 3300.0
Fare is 1650.0


In [3]:
#Problem-6
dict={

"and":"A logical operator",
"as": "To create an alias",
"break":"To get out of a loop",
"del": "To delete an obj",
"elif":"Used In conditional statements",
"else":"Used In conditional statements",
"except": "Used With exceptions, what to do when an exception occurs",
"False":"Boolean value, result of comparison operations",
"Finally":"Used With exceptions, a block of code that will be executed no matter If there Is an exception Or Not",
"for":"To create a  loop",
"from":"To Import specific parts of a module",
"if":"To make a conditional statement",
"global": "To declare a Global variable",
"import": "To Import a module",
"in": "To check If a value Is present In a List, Tuple, etc.",
"is": "To test If two variables are equal",
"lambda":"To create an anonymous function",
"Non":"Represents a null value",
"not":"A logical operator",
"or":"A logical operator",
"pass": "A null statement, a statement that will do nothing",
"raise":  "To Raise an exception",
"return": "To exit a function And Return a value",
"true":"Boolean value, result of comparison operations",
"nonlocal": "To declare a non-local variable",
"with": "Used to simplify exception handling" ,
"try":"To make a Try...Except statement",
"while": "To create a While loop"

}
def check(dict,key):
    if key in dict.keys():
        print("Reserved,",end="")
        print(key,"=",dict[key])
    else:
        print("Not Reserved")
key= str(input("Enter to Check")) 
check(dict,key)


Enter to Checkas
Reserved,as = To create an alias


In [14]:
#Problem-7

n=int(input (" Enter the number of rows:"))
list1=[[] for i in range (n)]

for i in range(n):
    for j in range(i+1):
        if (j<i):
            if(j==0):
                list1[i].append (1)
            else:
                list1[i].append(list1[i-1][j]+list1[i-1][j- 1])
        elif(i==j):
            list1[i].append(1)

for i in range(n):
    for j in range(i+1):
        print(list1[i][j], end=" ")       
    print()

 Enter the number of rows:7
1 
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 
1 5 10 10 5 1 
1 6 15 20 15 6 1 
